config/routes.rb
VoenbankRorPostgres::Application.routes.draw do
  root "loans#new"
  get "static_pages/:page_id", controller: "static_pages", action: "page", as: "static_page"
  post "/login", controller: "application", action: "login"
  get "/private_office/:id", controller: "admin", action: "private_office", as: "private_office"

  get "/feedback", controller: "static_pages", action: "feedback", as: "feedback"

  get "/logout", controller: "application", action: "logout"
  get '/user_cabinet', controller: 'application', action: 'user_cabinet'




  resources :stocks do
    post :stock_switch, on: :member
  end

  resources :feedbacks do
    get :admin, on: :collection
  end

  resources :partners do
    post :partner_switch, on: :member
    get :admin, on: :collection
  end

  resources :faqs do
    get :admin, on: :collection
  end

  resources :shares do
    post :share_switch, on: :member
    get :admin, on: :collection
  end

  resources :contact_messages do
    get :admin, on: :collection
  end

  resources :callbacks

  resource :users do
    get :user_nested_info, on: :collection
    get :index, on: :collection
    get '/:id/show', controller: 'users', action: 'show', as: :profile_page
    get '/:id/get_document', controller: 'users', action: 'get_document', as: :document

    resources :deposits do
      get 'deposit_request', on: :collection
      get 'deposits_contribution_list', on: :member

      resources :contribution_accounts

    end

    resources :loans do
      get 'loan_request', on: :collection
      post 'short_registration', on: :collection
      get 'loan_status', on: :member
      get 'user_loan_payment_history', on: :member
      resources :loan_repayments
    end
  end

  resources :percents do
    # get '/', controller: 'percents', action: 'admin'
  end

  resources :statistics

  resources :contract_documents

  resources :roles

  resources :roles_percents do
    get 'role_data_list', on: :collection
  end

  namespace :api do
    resources :users do
      post 'login', on: :collection
    end
  end
end

app/models/faq.rb
class Faq < ActiveRecord::Base

end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :check_admin, only: %w[admin new create edit update destroy]

  def index
    @faq = Faq.limit(10)
  end

  def admin
    @faq = Faq.all
  end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.new(faq_params)
    @faq.save
    redirect_to admin_faqs_path
  end

  def edit
    @faq = Faq.find(params[:id])
  end

  def update
    @faq = Faq.find(params[:id])
    if @faq.update_attributes(faq_params)
      flash.now[:notice] = "Вопрос/ответ успешно изменен"
      redirect_to admin_faqs_path
    else
      render :edit
    end
  end

  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy!
    render json: {success: true}
  end

  private

  def faq_params
    params.require(:faq).permit(:question, :answer)
  end
end

app/views/faqs/_form.html.slim
= form_for @faq, html: {class: 'form-horizontal'} do |f|
  .control-group
    = f.label "Вопрос"
    .controls
      = f.text_area :question, rows: 5
  .control-group
    = f.label "Ответ"
    .controls
      = f.text_area :answer, rows: 5
  .control-group
    = f.submit "Отправить"

app/views/faqs/admin.html.slim
= link_to 'Создать', new_faq_path, class: 'btn btn-warning'
table.table.table-bordered.stocks_info
  tr
    th = "Номер новости"
    th = "Заголовок"
    th = "Текст"
    th = "Изображение"
  - @faq.each do |faq|
    tr faq_id='#{faq.id}' class="faq_#{faq.id}"
      td.stock_id
        = faq.id
      td
        = faq.question[0..10]<<"..."
      td
        = faq.answer[0..10]<<"..."
      td
        = link_to "Редактировать", edit_faq_path(faq.id), class: "btn btn-primary"
      td
        = link_to "Удалить", "", class: "btn btn-danger faq_destroy", remote: true

app/views/faqs/edit.html.slim
.static_page.faq_page
  .static_page_title
    h2="FAQ - редактирование"
  = render "form"

app/views/faqs/index.html.slim
.static_page.faq_page
  .static_page_title
    h2="FAQ"
  - @faq.each do |faq|
    .faq_item
      .faq_question
        span.arrow.down
        p = faq.question
        .faq_answer
          = faq.answer

app/views/faqs/new.html.slim
.static_page
  .static_page_title
    h2="Создать вопрос/ответ"
  = render 'form'