config/routes.rb
VoenbankRorPostgres::Application.routes.draw do
  root "loans#new"
  get "static_pages/:page_id", controller: "static_pages", action: "page", as: "static_page"
  post "/login", controller: "application", action: "login"
  get "/private_office/:id", controller: "admin", action: "private_office", as: "private_office"

  get "/feedback", controller: "static_pages", action: "feedback", as: "feedback"

  get "/logout", controller: "application", action: "logout"
  get '/user_cabinet', controller: 'application', action: 'user_cabinet'




  resources :stocks do
    post :stock_switch, on: :member
  end

  resources :feedbacks do
    get :admin, on: :collection
  end

  resources :partners do
    post :partner_switch, on: :member
    get :admin, on: :collection
  end

  resources :faqs do
    get :admin, on: :collection
  end

  resources :shares do
    post :share_switch, on: :member
    get :admin, on: :collection
  end

  resources :contact_messages do
    get :admin, on: :collection
  end

  resources :callbacks

  resource :users do
    get :user_nested_info, on: :collection
    get :index, on: :collection
    get '/:id/show', controller: 'users', action: 'show', as: :profile_page
    get '/:id/get_document', controller: 'users', action: 'get_document', as: :document

    resources :deposits do
      get 'deposit_request', on: :collection
      get 'deposits_contribution_list', on: :member

      resources :contribution_accounts

    end

    resources :loans do
      get 'loan_request', on: :collection
      post 'short_registration', on: :collection
      get 'loan_status', on: :member
      get 'user_loan_payment_history', on: :member
      resources :loan_repayments
    end
  end

  resources :percents do
    # get '/', controller: 'percents', action: 'admin'
  end

  resources :statistics

  resources :contract_documents

  resources :roles

  resources :roles_percents do
    get 'role_data_list', on: :collection
  end

  namespace :api do
    resources :users do
      post 'login', on: :collection
    end
  end
end

app/models/share.rb
class Share < ActiveRecord::Base

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :check_admin, only: %w[admin new create edit update destroy]

  def index
    @share = Share.where(enabled: true)
  end

  def admin
    @share = Share.all
  end

  def create
    @share = Share.new(share_params)
    @share.save
    redirect_to admin_shares_path
  end

  def new
    @share = Share.new
  end

  def update
    @share = Share.find(params[:id])
    if @share.update_attributes(share_params)
      flash[:notice] = "Информация об акции успешно обновлена"
      redirect_to admin_shares_path
    else
      render :edit
    end
  end

  def show
    @share = Share.find(params[:id])
  end

  def edit
    @share = Share.find(params[:id])
  end

  def destroy
    @share = Share.find(params[:id])
    @share.destroy!
    render json: {success: true}
  end

  def share_switch
    @share = Share.find(params[:id])
    @share.update_attributes(enabled: !@share.enabled)
    result = @share.enabled ? {success: true} : {success: false}
    render json: result
  end

  private

  def share_params
    params.require(:share).permit(:share_title, :share_text)
  end
end

app/views/shares/_form.html.slim
= form_for @share, html: {class: 'form-horizontal'} do |f|
  .control-group
    = f.label "Название акции"
    .controls
      = f.text_field :share_title
  .control-group
    = f.label "Описание акции"
    .controls
      = f.text_area :share_text, rows: 5
  .control-group
    = f.submit "Отправить"

app/views/shares/admin.html.slim
= link_to 'Создать', new_share_path, class: 'btn btn-warning'
table.table.table-bordered.stocks_info
  tr
    th = "Номер акции"
    th = "Заголовок"
    th = "Текст"
  - @share.each do |share|
    tr share_id='#{share.id}' class="share_#{share.id}"
      td.stock_id
        = share.id
      td
        = share.share_title
      td
        = share.share_text
      td
        = link_to "Редактировать", edit_share_path(share.id), class: "btn btn-primary"
        = link_to "Удалить", "", class: "btn btn-danger share_destroy", remote: true
        - status, class_val = share.enabled ? "Не отображать" : "Отображать", share.enabled ? "btn-success" : "btn-warning"
        =link_to status, "",  class: "btn share-show #{class_val}", remote: true

app/views/shares/edit.html.slim
.partners_page
  .static_page_title
    h2="Редактировать акцию"
  = render "form"

app/views/shares/index.html.slim
.partners_page.share_page
  .static_page_title
    h2="Акции"
  - @share.each do |share|
    .share_item
      .share_question
        span.arrow.down
        p = share.share_title
        .share_answer
          = raw(share.share_text)

app/views/shares/new.html.slim
.partners_page
  .static_page_title
    h2="Создать акцию"
  = render "form"