config/routes.rb
VoenbankRorPostgres::Application.routes.draw do
  root "loans#new"
  get "static_pages/:page_id", controller: "static_pages", action: "page", as: "static_page"
  post "/login", controller: "application", action: "login"
  get "/private_office/:id", controller: "admin", action: "private_office", as: "private_office"

  get "/feedback", controller: "static_pages", action: "feedback", as: "feedback"

  get "/logout", controller: "application", action: "logout"
  get '/user_cabinet', controller: 'application', action: 'user_cabinet'




  resources :stocks do
    post :stock_switch, on: :member
  end

  resources :feedbacks do
    get :admin, on: :collection
  end

  resources :partners do
    post :partner_switch, on: :member
    get :admin, on: :collection
  end

  resources :faqs do
    get :admin, on: :collection
  end

  resources :shares do
    post :share_switch, on: :member
    get :admin, on: :collection
  end

  resources :contact_messages do
    get :admin, on: :collection
  end

  resources :callbacks

  resource :users do
    get :user_nested_info, on: :collection
    get :index, on: :collection
    get '/:id/show', controller: 'users', action: 'show', as: :profile_page
    get '/:id/get_document', controller: 'users', action: 'get_document', as: :document

    resources :deposits do
      get 'deposit_request', on: :collection
      get 'deposits_contribution_list', on: :member

      resources :contribution_accounts

    end

    resources :loans do
      get 'loan_request', on: :collection
      post 'short_registration', on: :collection
      get 'loan_status', on: :member
      get 'user_loan_payment_history', on: :member
      resources :loan_repayments
    end
  end

  resources :percents do
    # get '/', controller: 'percents', action: 'admin'
  end

  resources :statistics

  resources :contract_documents

  resources :roles

  resources :roles_percents do
    get 'role_data_list', on: :collection
  end

  namespace :api do
    resources :users do
      post 'login', on: :collection
    end
  end
end

app/views/shared/_callback.html.slim
.callback_form
  .callback_title
    p = "Обратный звонок"
  .callback_main
    = form_tag('/callbacks/new', method: 'post', html: { class: "callback_form" })
      = text_field_tag :surname, nil,  placeholder: 'Фамилия'
      = text_field_tag :name, nil, placeholder: 'Имя'
      = text_field_tag :second_name, nil, placeholder: 'Отчество'
      = text_field_tag :phone, nil, placeholder: 'Телефон'
      = text_field_tag :email, nil, placeholder: 'email'
      = submit_tag ' Заказать звонок'

app/views/shared/_footer.html.slim
.footer
  .left_part
    p= "ООО 'Независимое финансовое объединение'(свидетельство ЦБ РФ 65-13-031-40-004585). Предложение не является публичной офертой.Все права защищены. Санкт-Петербург 2014"
  .right_part
    p = "служба поддержки 8(812)950-10-98 8(812)382-89-09 info@voenbank.ru"

app/views/shared/admin_panel.html.slim
.btn-group.admin-panel
  = link_to 'Пользователи', users_path, class: 'btn'
  = link_to 'Обратный звонок', callbacks_path, class: 'btn'
  = link_to 'Обратная связь', admin_feedbacks_path, class: 'btn'
  = link_to 'Партнеры', admin_partners_path, class: 'btn'
  = link_to 'Новости', stocks_path, class: 'btn'
  = link_to 'FAQ', admin_faqs_path, class: 'btn'
  = link_to 'Акции', admin_shares_path, class: 'btn'
  = link_to 'Контакты', admin_contact_messages_path, class: 'btn'
  = link_to 'Проценты', percents_path, class: 'btn'
  = link_to 'Договор', contract_documents_path, class: 'btn'
  = link_to 'Проценты для роли', roles_percents_path, class: 'btn'

app/views/shared/authorization.html.slim
.authorization
  = form_tag("/login", method: :post) do
    = text_field_tag :login, "", placeholder: "Логин", class: "auth_login"
    = password_field_tag :password, "", placeholder: "Пароль", class: "auth_pass"
    = submit_tag("Войти", class: "submit_login")

app/views/shared/main_head.html.slim
header.header
  .logotype_vb
    = link_to root_path do
      =image_tag "vb-logo.png"
  .callback_phone
    p = "Номер обратной связи"
    p = "(812) 950-10-98"
  - if current_user
    = render template: "shared/user_head"
  -else
    = render template: "shared/authorization"

app/views/shared/news_slider.html.slim
- news_slider = Stock.where(enabled: true)
.news_slider.slider
  ul
   - news_slider.each do |news|
    li
      = image_tag(news.image.url(:normal))  if news.image.file?

app/views/shared/page_title.html.slim
.static_page
  .static_page_title
    h2= title

app/views/shared/user_head.html.slim
.user_info
  .greetings
    p= "Здравствуйте,"
    p.user_full_name= "#{current_user.full_name}"
    - if current_user.is_admin?
      p="АДМИНИСТРАТОР"

  .user_actions
    = link_to "Личный кабинет", "#", remote: true, class: 'btn user_cabinet', data: {user: current_user.id}
    = link_to "Выйти", logout_path(logout: true),  class: 'btn logout-button'