config/routes.rb
VoenbankRorPostgres::Application.routes.draw do
  root "loans#new"
  get "static_pages/:page_id", controller: "static_pages", action: "page", as: "static_page"
  post "/login", controller: "application", action: "login"
  get "/private_office/:id", controller: "admin", action: "private_office", as: "private_office"

  get "/feedback", controller: "static_pages", action: "feedback", as: "feedback"

  get "/logout", controller: "application", action: "logout"
  get '/user_cabinet', controller: 'application', action: 'user_cabinet'




  resources :stocks do
    post :stock_switch, on: :member
  end

  resources :feedbacks do
    get :admin, on: :collection
  end

  resources :partners do
    post :partner_switch, on: :member
    get :admin, on: :collection
  end

  resources :faqs do
    get :admin, on: :collection
  end

  resources :shares do
    post :share_switch, on: :member
    get :admin, on: :collection
  end

  resources :contact_messages do
    get :admin, on: :collection
  end

  resources :callbacks

  resource :users do
    get :user_nested_info, on: :collection
    get :index, on: :collection
    get '/:id/show', controller: 'users', action: 'show', as: :profile_page
    get '/:id/get_document', controller: 'users', action: 'get_document', as: :document

    resources :deposits do
      get 'deposit_request', on: :collection
      get 'deposits_contribution_list', on: :member

      resources :contribution_accounts

    end

    resources :loans do
      get 'loan_request', on: :collection
      post 'short_registration', on: :collection
      get 'loan_status', on: :member
      get 'user_loan_payment_history', on: :member
      resources :loan_repayments
    end
  end

  resources :percents do
    # get '/', controller: 'percents', action: 'admin'
  end

  resources :statistics

  resources :contract_documents

  resources :roles

  resources :roles_percents do
    get 'role_data_list', on: :collection
  end

  namespace :api do
    resources :users do
      post 'login', on: :collection
    end
  end
end

app/models/deposit.rb
 class Deposit < ActiveRecord::Base
  belongs_to :user
  has_many :percent
  has_many :contribution_account
  validates_presence_of :deposit_current_summ, :percent_id
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController

  def new
    @user = User.new
    @deposit = @user.deposits.build
  end

  def create
    @user = User.new(user_params)
    @user.save
    flash[:notice] = "Спасибо за вклад!"
    redirect_to root_path
  end

  def deposit_request
    if @current_user
      current_user_new_deposit(@current_user)
      render json: {response: 'Спасибо за ваш вклад!'}
    else
      new
      render  partial: 'deposit_request',
              locals: { current_amount: params[:amount],
                        percent: Percent.find_by_value(0.42).id
              },
              layout: false
    end

  end

  def deposits_contribution_list
    deposit = Deposit.find(params[:id])
    @payment = ContributionAccount.where(deposit_id: deposit.id)
  end

  private

  def user_params
    params.require(:user).permit(:surname, :name, :secondname, :contact_phone, deposits_attributes: [:id, :user_id, :deposit_current_summ, :percent_id])
  end

  def current_user_new_deposit(user)
    Deposit.create(user_id: user.id, deposit_current_summ: params[:amount], percent_id: params[:percent])
  end

end

app/views/deposits/_deposit_calc.html.slim
.deposit_calc_wrapper
  .calc_deposit
    .slider_deposit_amount
      .deposit_amount
        span="Мне надо приумножить:"
        = text_field_tag nil, nil, class: 'deposit_amount_value'
      .slider_wrapper
        span.left_slider_arrow
        span.right_slider_arrow
        #slider_deposit_amount
      .amount_range
        .range_1 = "100 тыс."
        .range_2 = "500 тыс."
        .range_3 = "1 м."
        .range_4 = "1.5 м."
        .range_5 = "2 м."
        .range_6 = "2.5"
        .range_7 = "3 м."

      .slider_divider
    .slider_deposit_time
      .deposit_time
        span = "За время:"
        = text_field_tag nil, nil, class: 'deposit_time_value'
      .slider_wrapper
        span.left_slider_arrow
        span.right_slider_arrow
        #slider_deposit_time
      .time_range
        .range_1 = "1"
        .range_2 = "2"
        .range_3 = "3"
      .slider_divider
    .percents_chose
      .slider_percent
        .main_percent_slider
          p = "Проценты:"
          p.left_side.active = "Добавлять проценты ко вкладу"
          p.right_side = "Забирать проценты по итогу расчетного периода"
          #percents_slider
    = button_tag 'Получить денежное довольствие', class: 'deposit_confirm'
  .vertical_divider_line
  .deposit_diagram
    .deposit_diagram_wrapper
      .deposit_left_diagram
        .deposit_info_user
          p = "Вложил"
          p.user_amount
        .deposit_diagram_top
        .deposit_diagram_middle
          .deposit_diagram_middle_top
          .deposit_diagram_middle_middle
          .deposit_diagram_middle_bottom
        .deposit_diagram_bottom
      .deposit_right_diagram
        .deposit_info_user
          p = "Забрал"
          p.user_full_summ
        .deposit_profit_diagram_top
        .deposit_profit_diagram_middle
          .deposit_diagram_middle_top
          .deposit_diagram_middle_middle
          .deposit_diagram_middle_bottom
        .deposit_diagram_top
        .deposit_diagram_middle
          .deposit_diagram_middle_top
          .deposit_diagram_middle_middle
          .deposit_diagram_middle_bottom
        .deposit_diagram_bottom
    .deposit_information
      .main_title
        span = "За "
        span.month_count
        span=" месяцев я получу "
      p.current_summ
      .optional_info
        p = "Из них"
        ul.pay_list
          li
            p="Мой вклад:"
            p.user_deposit
          li
            p="Начисленные проценты:"
            p.added_percents

app/views/deposits/_deposit_list.html.slim
- current_user.deposits.each do |deposit|
  .deposit_list_item
    .deposit_list_item_title.closed
      p= "#{deposit.created_at.to_date} - #{deposit.deposit_current_summ} р."
      span.arrow.down
    .deposit_list_item_body.hide
      .list_body_cell
        p.title= "Сумма вклада: "
        p.value= "#{deposit.deposit_current_summ} р."
      .list_body_cell
        p.title= "Дата начала: "
        p.value= "#{deposit.created_at.to_date}"
      .list_body_cell
        = link_to 'Просмотр истории вклада', deposits_contribution_list_users_deposit_path(id: deposit.id)

app/views/deposits/_deposit_request.html.slim
.deposit_request
  = form_for @user, url: '/users/deposits' do |f|
      .deposit_form_item
        = f.label "Фамилия:"
        = f.text_field :surname
      .deposit_form_item
        = f.label "Имя:"
        = f.text_field  :name
      .deposit_form_item
        = f.label "Отчество:"
        = f.text_field  :secondname
      .deposit_form_item
        = f.label "Контактный телефон:"
        = f.text_field :contact_phone
      = f.fields_for :deposits do |deposit|
        = deposit.hidden_field :deposit_current_summ, value: current_amount
        = deposit.hidden_field :percent_id, value: percent
      = f.submit 'Оставить заявку', class: 'deposit_form_submit'

app/views/deposits/deposits_contribution_list.html.slim
= link_to "&larr; На страницу вкладов пользователя".html_safe, new_users_deposit_path, class: 'brn brn-warning'
table.table.table-bordered
  tr
    th= "ID:"
    th= "Дата:"
    th= "Внесенная сумма:"
    th= "Тип операции"
  - @payment.each do |pay|
    tr
      td= pay.id
      td= pay.created_at
      td= pay.operation_summ
      td= pay.removed_brought ? "Внесена" :  "Снята"

app/views/deposits/new.html.slim
.static_page.deposit_page
  .static_page_title
    h2="Калькулятор вклада"
  - if current_user
    .deposit_calc.main_temp
      .deposit_calc_title.closed
        p="Калькулятор депозита"
        span.arrow.down
      .deposit_calc_body.body_partial.hide
        = render 'deposit_calc'
    .deposit_list.main_temp
      .deposit_list_title.closed
        p="Список вкладов"
        span.arrow.down
      .deposit_list_body.body_partial.hide
        = render 'deposit_list'
  - else
    = render 'deposit_calc'